/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_automatak_dnp3_impl_CommandBuilderImpl */

#ifndef _Included_com_automatak_dnp3_impl_CommandBuilderImpl
#define _Included_com_automatak_dnp3_impl_CommandBuilderImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_automatak_dnp3_impl_CommandBuilderImpl
 * Method:    create_native
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_automatak_dnp3_impl_CommandBuilderImpl_create_1native
  (JNIEnv *, jobject);

/*
 * Class:     com_automatak_dnp3_impl_CommandBuilderImpl
 * Method:    destroy_native
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_automatak_dnp3_impl_CommandBuilderImpl_destroy_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_automatak_dnp3_impl_CommandBuilderImpl
 * Method:    add_crob_native
 * Signature: (JLjava/lang/Iterable;)V
 */
JNIEXPORT void JNICALL Java_com_automatak_dnp3_impl_CommandBuilderImpl_add_1crob_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_automatak_dnp3_impl_CommandBuilderImpl
 * Method:    add_aoI16_native
 * Signature: (JLjava/lang/Iterable;)V
 */
JNIEXPORT void JNICALL Java_com_automatak_dnp3_impl_CommandBuilderImpl_add_1aoI16_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_automatak_dnp3_impl_CommandBuilderImpl
 * Method:    add_aoI32_native
 * Signature: (JLjava/lang/Iterable;)V
 */
JNIEXPORT void JNICALL Java_com_automatak_dnp3_impl_CommandBuilderImpl_add_1aoI32_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_automatak_dnp3_impl_CommandBuilderImpl
 * Method:    add_aoF32_native
 * Signature: (JLjava/lang/Iterable;)V
 */
JNIEXPORT void JNICALL Java_com_automatak_dnp3_impl_CommandBuilderImpl_add_1aoF32_1native
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_automatak_dnp3_impl_CommandBuilderImpl
 * Method:    add_aoD64_native
 * Signature: (JLjava/lang/Iterable;)V
 */
JNIEXPORT void JNICALL Java_com_automatak_dnp3_impl_CommandBuilderImpl_add_1aoD64_1native
  (JNIEnv *, jobject, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
