/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_automatak_dnp3_impl_ChangeSetImpl */

#ifndef _Included_com_automatak_dnp3_impl_ChangeSetImpl
#define _Included_com_automatak_dnp3_impl_ChangeSetImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_automatak_dnp3_impl_ChangeSetImpl
 * Method:    create_instance_native
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_automatak_dnp3_impl_ChangeSetImpl_create_1instance_1native
  (JNIEnv *, jobject);

/*
 * Class:     com_automatak_dnp3_impl_ChangeSetImpl
 * Method:    destroy_instance_native
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_automatak_dnp3_impl_ChangeSetImpl_destroy_1instance_1native
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_automatak_dnp3_impl_ChangeSetImpl
 * Method:    update_binary_native
 * Signature: (JZBJII)V
 */
JNIEXPORT void JNICALL Java_com_automatak_dnp3_impl_ChangeSetImpl_update_1binary_1native
  (JNIEnv *, jobject, jlong, jboolean, jbyte, jlong, jint, jint);

/*
 * Class:     com_automatak_dnp3_impl_ChangeSetImpl
 * Method:    update_double_binary_native
 * Signature: (JIBJII)V
 */
JNIEXPORT void JNICALL Java_com_automatak_dnp3_impl_ChangeSetImpl_update_1double_1binary_1native
  (JNIEnv *, jobject, jlong, jint, jbyte, jlong, jint, jint);

/*
 * Class:     com_automatak_dnp3_impl_ChangeSetImpl
 * Method:    update_analog_native
 * Signature: (JDBJII)V
 */
JNIEXPORT void JNICALL Java_com_automatak_dnp3_impl_ChangeSetImpl_update_1analog_1native
  (JNIEnv *, jobject, jlong, jdouble, jbyte, jlong, jint, jint);

/*
 * Class:     com_automatak_dnp3_impl_ChangeSetImpl
 * Method:    update_counter_native
 * Signature: (JJBJII)V
 */
JNIEXPORT void JNICALL Java_com_automatak_dnp3_impl_ChangeSetImpl_update_1counter_1native
  (JNIEnv *, jobject, jlong, jlong, jbyte, jlong, jint, jint);

/*
 * Class:     com_automatak_dnp3_impl_ChangeSetImpl
 * Method:    update_frozen_counter_native
 * Signature: (JJBJII)V
 */
JNIEXPORT void JNICALL Java_com_automatak_dnp3_impl_ChangeSetImpl_update_1frozen_1counter_1native
  (JNIEnv *, jobject, jlong, jlong, jbyte, jlong, jint, jint);

/*
 * Class:     com_automatak_dnp3_impl_ChangeSetImpl
 * Method:    update_bo_status_native
 * Signature: (JZBJII)V
 */
JNIEXPORT void JNICALL Java_com_automatak_dnp3_impl_ChangeSetImpl_update_1bo_1status_1native
  (JNIEnv *, jobject, jlong, jboolean, jbyte, jlong, jint, jint);

/*
 * Class:     com_automatak_dnp3_impl_ChangeSetImpl
 * Method:    update_ao_status_native
 * Signature: (JDBJII)V
 */
JNIEXPORT void JNICALL Java_com_automatak_dnp3_impl_ChangeSetImpl_update_1ao_1status_1native
  (JNIEnv *, jobject, jlong, jdouble, jbyte, jlong, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
