/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_automatak_dnp3_impl_DNP3ManagerFactory */

#ifndef _Included_com_automatak_dnp3_impl_DNP3ManagerFactory
#define _Included_com_automatak_dnp3_impl_DNP3ManagerFactory
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
